### ISSUE TITLE
features - todo

### ISSUE THREAD

**Issue by ats1999** [ats1999/md-byte#18]
- [x] in browser full screen using key
- [x] complete  window full screen using  key
- [ ] https://github.com/ats1999/md-byte/issues/13
- [ ] https://github.com/ats1999/md-byte/issues/3
- [ ] https://github.com/ats1999/md-byte/issues/4
- [ ] https://github.com/ats1999/md-byte/issues/9
- [ ] https://github.com/ats1999/md-byte/issues/10
